version: "3.8"

services:
  # postgres:
  #   image: postgres:15.3 # Specify your desired version
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: PCDACODB
  #   ports:
  #     - "5432:5432" # Expose PostgreSQL on localhost
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data # Persist data across container restarts

  postgis:
    image: postgis/postgis:13-3.1
    container_name: postgis_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PCDACODB
    restart: unless-stopped
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost

volumes:
  postgres_data:
