using Domain.Constants.EntityNames;
using Domain.Entities;
using Domain.Enums;
using NetTopologySuite.Geometries;
using UseCases.Utils;
using UUIDNext;

namespace Persistance.Bogus;

public class CarDummyData
{
    public required string Color { get; set; }
    public required int Seat { get; set; }
    public required decimal FuelConsumption { get; set; }
    public required decimal Price { get; set; }
    public required string LicensePlate { get; set; }
    public required CarStatusEnum Status { get; set; }
    public required string FuelType { get; set; }
    public required string TransmissionType { get; set; }
    public required string Model { get; set; }
    public required double Latitude { get; set; }
    public required double Longitude { get; set; }
    public required string Address { get; set; }
}

public class CarGenerator
{
    public static readonly CarDummyData[] Cars =
    [
        new()
        {
            Color = "Red",
            Seat = 5,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "55132",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Mustang",
            Latitude = 10.7756587,
            Longitude = 106.7004238,
            Address = "268 Nam Kỳ Khởi Nghĩa, Phường 8, Quận 3, TP.HCM"
        },
        new()
        {
            Color = "Green",
            Seat = 5,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "13622",
            Status = CarStatusEnum.Pending,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Suburban",
            Latitude = 10.8456809,
            Longitude = 106.7921667,
            Address = "Đường D1, Phường Long Thạnh Mỹ, TP. Thủ Đức, TP.HCM"
        },
        new()
        {
            Color = "Yellow",
            Seat = 9,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "99132",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Tiguan",
            Latitude = 10.7285605,
            Longitude = 106.7218072,
            Address = "1 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM"
        },
        new()
        {
            Color = "Black",
            Seat = 9,
            FuelConsumption = 0.75M,
            Price = 100000,
            LicensePlate = "55555",
            Status = CarStatusEnum.Rented,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Pathfinder",
            Latitude = 10.8105831,
            Longitude = 106.7091422,
            Address = "232 Điện Biên Phủ, Phường 17, Bình Thạnh, TP.HCM"
        },
        // new 20 cars with Available status
        new()
        {
            Color = "Red",
            Seat = 5,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "55132",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Mustang",
            Latitude = 10.7756587,
            Longitude = 106.7004238,
            Address = "268 Nam Kỳ Khởi Nghĩa, Phường 8, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Green",
            Seat = 5,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "13622",
            Status = CarStatusEnum.Pending,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Suburban",
            Latitude = 10.8456809,
            Longitude = 106.7921667,
            Address = "Đường D1, Phường Long Thạnh Mỹ, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Yellow",
            Seat = 9,
            FuelConsumption = 0.75M,
            Price = 30000,
            LicensePlate = "99132",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Tiguan",
            Latitude = 10.7285605,
            Longitude = 106.7218072,
            Address = "1 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
        },
        new()
        {
            Color = "Black",
            Seat = 9,
            FuelConsumption = 0.75M,
            Price = 100000,
            LicensePlate = "55555",
            Status = CarStatusEnum.Rented,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Pathfinder",
            Latitude = 10.8105831,
            Longitude = 106.7091422,
            Address = "232 Điện Biên Phủ, Phường 17, Bình Thạnh, TP.HCM",
        },
        // 20 new cars with Available status
        new()
        {
            Color = "White",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 45000,
            LicensePlate = "51A-12345",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Camry",
            Latitude = 10.7825,
            Longitude = 106.6958,
            Address = "123 Lê Lợi, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Silver",
            Seat = 7,
            FuelConsumption = 0.78M,
            Price = 50000,
            LicensePlate = "51A-23456",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Fortuner",
            Latitude = 10.7714,
            Longitude = 106.6977,
            Address = "45 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Blue",
            Seat = 4,
            FuelConsumption = 0.55M,
            Price = 38000,
            LicensePlate = "51A-34567",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model 3",
            Latitude = 10.7632,
            Longitude = 106.6822,
            Address = "76 Hai Bà Trưng, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Gray",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 42000,
            LicensePlate = "51A-45678",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Civic",
            Latitude = 10.7880,
            Longitude = 106.7024,
            Address = "215 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Pearl White",
            Seat = 7,
            FuelConsumption = 0.75M,
            Price = 55000,
            LicensePlate = "51A-56789",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Santa Fe",
            Latitude = 10.8016,
            Longitude = 106.7133,
            Address = "348 Võ Văn Ngân, Phường Bình Thọ, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Maroon",
            Seat = 5,
            FuelConsumption = 0.68M,
            Price = 48000,
            LicensePlate = "51A-67890",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "3 Series",
            Latitude = 10.7529,
            Longitude = 106.7234,
            Address = "90 Nguyễn Hữu Cảnh, Phường 22, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Black",
            Seat = 5,
            FuelConsumption = 0.60M,
            Price = 60000,
            LicensePlate = "51A-78901",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "A4",
            Latitude = 10.7725,
            Longitude = 106.7031,
            Address = "150 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Champagne",
            Seat = 7,
            FuelConsumption = 0.80M,
            Price = 52000,
            LicensePlate = "51A-89012",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Everest",
            Latitude = 10.7982,
            Longitude = 106.6763,
            Address = "235 Hoàng Văn Thụ, Phường 8, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Dark Green",
            Seat = 9,
            FuelConsumption = 0.85M,
            Price = 65000,
            LicensePlate = "51A-90123",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Suburban",
            Latitude = 10.8014,
            Longitude = 106.6469,
            Address = "120 Phan Xích Long, Phường 2, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Navy Blue",
            Seat = 5,
            FuelConsumption = 0.70M,
            Price = 40000,
            LicensePlate = "51A-01234",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Focus",
            Latitude = 10.7311,
            Longitude = 106.7315,
            Address = "1060 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
        },
        new()
        {
            Color = "Burgundy",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 45000,
            LicensePlate = "51A-12300",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model Y",
            Latitude = 10.7212,
            Longitude = 106.7195,
            Address = "72 Lê Văn Lương, Tân Quy, Quận 7, TP.HCM",
        },
        new()
        {
            Color = "Beige",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 38000,
            LicensePlate = "51A-23400",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Corolla",
            Latitude = 10.7954,
            Longitude = 106.7248,
            Address = "200 Xô Viết Nghệ Tĩnh, Phường 21, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Dark Gray",
            Seat = 7,
            FuelConsumption = 0.75M,
            Price = 58000,
            LicensePlate = "51A-34500",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Ranger",
            Latitude = 10.8482,
            Longitude = 106.7808,
            Address = "15 Võ Văn Ngân, Linh Chiểu, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Metallic Blue",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 47000,
            LicensePlate = "51A-45600",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "5 Series",
            Latitude = 10.7868,
            Longitude = 106.8045,
            Address = "300 Đỗ Xuân Hợp, Phước Long B, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Graphite",
            Seat = 7,
            FuelConsumption = 0.72M,
            Price = 54000,
            LicensePlate = "51A-56700",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "CR-V",
            Latitude = 10.8305,
            Longitude = 106.7903,
            Address = "8 Lê Văn Chí, Linh Trung, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Cherry Red",
            Seat = 5,
            FuelConsumption = 0.66M,
            Price = 42000,
            LicensePlate = "51A-67800",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Accord",
            Latitude = 10.7125,
            Longitude = 106.7257,
            Address = "489 Huỳnh Tấn Phát, Tân Thuận Đông, Quận 7, TP.HCM",
        },
        new()
        {
            Color = "Olive Green",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 39000,
            LicensePlate = "51A-78900",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Elantra",
            Latitude = 10.7548,
            Longitude = 106.6545,
            Address = "196 Phạm Văn Hai, Phường 5, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Midnight Blue",
            Seat = 7,
            FuelConsumption = 0.70M,
            Price = 51000,
            LicensePlate = "51A-89100",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Palisade",
            Latitude = 10.7733,
            Longitude = 106.6576,
            Address = "356 Cộng Hòa, Phường 13, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Platinum",
            Seat = 5,
            FuelConsumption = 0.58M,
            Price = 44000,
            LicensePlate = "51A-90120",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model S",
            Latitude = 10.7558,
            Longitude = 106.6416,
            Address = "78 Lý Thường Kiệt, Phường 7, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Charcoal",
            Seat = 5,
            FuelConsumption = 0.68M,
            Price = 49000,
            LicensePlate = "51A-01230",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "ES",
            Latitude = 10.8192,
            Longitude = 106.6291,
            Address = "51 Quang Trung, Phường 10, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Ruby Red",
            Seat = 7,
            FuelConsumption = 0.73M,
            Price = 53000,
            LicensePlate = "51A-22334",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Explorer",
            Latitude = 10.8348,
            Longitude = 106.6452,
            Address = "200 Nguyễn Văn Lượng, Phường 17, Gò Vấp, TP.HCM",
        },
        // add new 100 cars with available status
        new()
        {
            Color = "White Pearl",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 46000,
            LicensePlate = "51A-33445",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Camry",
            Latitude = 10.8362,
            Longitude = 106.6413,
            Address = "250 Nguyễn Văn Lượng, Phường 10, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Storm Gray",
            Seat = 7,
            FuelConsumption = 0.74M,
            Price = 57000,
            LicensePlate = "51A-44556",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Land Cruiser",
            Latitude = 10.8274,
            Longitude = 106.6537,
            Address = "35 Quang Trung, Phường 11, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Deep Blue",
            Seat = 4,
            FuelConsumption = 0.56M,
            Price = 42000,
            LicensePlate = "51A-55667",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model X",
            Latitude = 10.8157,
            Longitude = 106.6649,
            Address = "125 Lê Đức Thọ, Phường 6, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Silver Metallic",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 48000,
            LicensePlate = "51A-66778",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Corolla",
            Latitude = 10.8049,
            Longitude = 106.6746,
            Address = "78 Phan Văn Trị, Phường 5, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Obsidian Black",
            Seat = 5,
            FuelConsumption = 0.61M,
            Price = 54000,
            LicensePlate = "51A-77889",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "C-Class",
            Latitude = 10.7951,
            Longitude = 106.6872,
            Address = "167 Nguyễn Kiệm, Phường 3, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Racing Red",
            Seat = 2,
            FuelConsumption = 0.90M,
            Price = 120000,
            LicensePlate = "51A-88990",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "911",
            Latitude = 10.7724,
            Longitude = 106.7127,
            Address = "23 Điện Biên Phủ, Phường 22, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Emerald Green",
            Seat = 7,
            FuelConsumption = 0.77M,
            Price = 65000,
            LicensePlate = "51A-99001",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "GLE",
            Latitude = 10.7842,
            Longitude = 106.6989,
            Address = "189 Phan Đăng Lưu, Phường 1, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Sunset Orange",
            Seat = 5,
            FuelConsumption = 0.69M,
            Price = 55000,
            LicensePlate = "51A-00112",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "RAV4",
            Latitude = 10.7932,
            Longitude = 106.6876,
            Address = "56 Trần Huy Liệu, Phường 12, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Arctic White",
            Seat = 4,
            FuelConsumption = 0.57M,
            Price = 47000,
            LicensePlate = "51A-11223",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "I-PACE",
            Latitude = 10.8034,
            Longitude = 106.6743,
            Address = "102 Huỳnh Văn Bánh, Phường 15, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Sapphire Blue",
            Seat = 5,
            FuelConsumption = 0.68M,
            Price = 53000,
            LicensePlate = "51A-22334",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "3 Series",
            Latitude = 10.7895,
            Longitude = 106.6691,
            Address = "45 Nguyễn Văn Đậu, Phường 6, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Midnight Black",
            Seat = 7,
            FuelConsumption = 0.76M,
            Price = 62000,
            LicensePlate = "51A-33445",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Q7",
            Latitude = 10.7765,
            Longitude = 106.6945,
            Address = "78 Trần Quang Diệu, Phường 14, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Titanium Gray",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 49000,
            LicensePlate = "51A-44556",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Sonata",
            Latitude = 10.7853,
            Longitude = 106.7037,
            Address = "156 Hai Bà Trưng, Phường Đa Kao, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Wine Red",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 46000,
            LicensePlate = "51A-55667",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Mazda3",
            Latitude = 10.7623,
            Longitude = 106.6921,
            Address = "212 Võ Thị Sáu, Phường 7, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Champagne Gold",
            Seat = 7,
            FuelConsumption = 0.72M,
            Price = 58000,
            LicensePlate = "51A-66778",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Fortuner",
            Latitude = 10.7743,
            Longitude = 106.6812,
            Address = "78 Cao Thắng, Phường 4, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Ice Silver",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 51000,
            LicensePlate = "51A-77889",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Civic",
            Latitude = 10.7854,
            Longitude = 106.6721,
            Address = "134 Nguyễn Đình Chiểu, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Forest Green",
            Seat = 5,
            FuelConsumption = 0.69M,
            Price = 53000,
            LicensePlate = "51A-88990",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Golf",
            Latitude = 10.7954,
            Longitude = 106.6634,
            Address = "45 Cách Mạng Tháng Tám, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Royal Blue",
            Seat = 4,
            FuelConsumption = 0.55M,
            Price = 45000,
            LicensePlate = "51A-99001",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Taycan",
            Latitude = 10.7834,
            Longitude = 106.7053,
            Address = "67 Mạc Đĩnh Chi, Phường Đa Kao, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Pure White",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 46000,
            LicensePlate = "51A-00112",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Accord",
            Latitude = 10.7724,
            Longitude = 106.6964,
            Address = "23 Phạm Ngọc Thạch, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Cherry Black",
            Seat = 5,
            FuelConsumption = 0.66M,
            Price = 49000,
            LicensePlate = "51A-11223",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Mazda6",
            Latitude = 10.7634,
            Longitude = 106.6831,
            Address = "189 Nam Kỳ Khởi Nghĩa, Phường 7, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Dolphin Gray",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 47000,
            LicensePlate = "51A-22334",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "XC60",
            Latitude = 10.7864,
            Longitude = 106.6742,
            Address = "56 Lý Chính Thắng, Phường 8, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Burgundy Red",
            Seat = 7,
            FuelConsumption = 0.74M,
            Price = 60000,
            LicensePlate = "51A-33445",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Santa Fe",
            Latitude = 10.7754,
            Longitude = 106.6652,
            Address = "123 Nguyễn Thị Minh Khai, Phường 5, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Dark Blue",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 48000,
            LicensePlate = "51A-44556",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "CX-5",
            Latitude = 10.7654,
            Longitude = 106.6743,
            Address = "56 Hồ Xuân Hương, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Platinum Silver",
            Seat = 7,
            FuelConsumption = 0.68M,
            Price = 53000,
            LicensePlate = "51A-55667",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Highlander",
            Latitude = 10.7724,
            Longitude = 106.6834,
            Address = "78 Lê Văn Sỹ, Phường 12, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "British Racing Green",
            Seat = 4,
            FuelConsumption = 0.58M,
            Price = 70000,
            LicensePlate = "51A-66778",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "F-TYPE",
            Latitude = 10.7833,
            Longitude = 106.6922,
            Address = "123 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Urban Gray",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 49000,
            LicensePlate = "51A-77889",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "ES",
            Latitude = 10.7943,
            Longitude = 106.7034,
            Address = "56 Xô Viết Nghệ Tĩnh, Phường 19, Bình Thạnh, TP.HCM",
        },
        // 25
        new()
        {
            Color = "Pearl Navy",
            Seat = 7,
            FuelConsumption = 0.69M,
            Price = 56000,
            LicensePlate = "51A-12421",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Palisade",
            Latitude = 10.8025,
            Longitude = 106.7144,
            Address = "45 Nguyễn Thị Minh Khai, Phường 1, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Cosmic Black",
            Seat = 5,
            FuelConsumption = 0.61M,
            Price = 52500,
            LicensePlate = "51A-78542",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Tucson",
            Latitude = 10.7891,
            Longitude = 106.6963,
            Address = "78 Lê Duẩn, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Starlight Silver",
            Seat = 5,
            FuelConsumption = 0.59M,
            Price = 47500,
            LicensePlate = "51A-89654",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "K5",
            Latitude = 10.7756,
            Longitude = 106.7023,
            Address = "123 Trần Hưng Đạo, Phường 3, Quận 5, TP.HCM",
        },
        new()
        {
            Color = "Ocean Blue",
            Seat = 4,
            FuelConsumption = 0.53M,
            Price = 63000,
            LicensePlate = "51A-65432",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "EV6",
            Latitude = 10.8136,
            Longitude = 106.6780,
            Address = "56 Trường Sơn, Phường 2, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Alpine White",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 58000,
            LicensePlate = "51A-98765",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "X3",
            Latitude = 10.8023,
            Longitude = 106.6512,
            Address = "234 Phan Xích Long, Phường 1, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Racing Yellow",
            Seat = 2,
            FuelConsumption = 0.85M,
            Price = 135000,
            LicensePlate = "51A-34567",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "718 Cayman",
            Latitude = 10.7712,
            Longitude = 106.7045,
            Address = "567 Nguyễn Đình Chiểu, Phường 5, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Forest Mist",
            Seat = 7,
            FuelConsumption = 0.71M,
            Price = 54000,
            LicensePlate = "51A-87634",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Everest",
            Latitude = 10.8327,
            Longitude = 106.8176,
            Address = "789 Tô Ngọc Vân, Linh Tây, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Electric Blue",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 49500,
            LicensePlate = "51A-54378",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Jetta",
            Latitude = 10.7632,
            Longitude = 106.6542,
            Address = "98 Cộng Hòa, Phường 4, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Charcoal Grey",
            Seat = 5,
            FuelConsumption = 0.60M,
            Price = 44500,
            LicensePlate = "51A-67854",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Forte",
            Latitude = 10.7523,
            Longitude = 106.7176,
            Address = "321 Khánh Hội, Phường 1, Quận 4, TP.HCM",
        },
        new()
        {
            Color = "Ruby Metallic",
            Seat = 5,
            FuelConsumption = 0.66M,
            Price = 51000,
            LicensePlate = "51A-43219",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "CX-30",
            Latitude = 10.7891,
            Longitude = 106.6234,
            Address = "654 Lý Thường Kiệt, Phường 6, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Phantom Black",
            Seat = 7,
            FuelConsumption = 0.72M,
            Price = 59000,
            LicensePlate = "51A-32145",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Sorento",
            Latitude = 10.8145,
            Longitude = 106.7312,
            Address = "123 Quang Trung, Phường 10, Gò Vấp, TP.HCM",
        },
        new()
        {
            Color = "Deep Aqua",
            Seat = 5,
            FuelConsumption = 0.58M,
            Price = 46500,
            LicensePlate = "51A-56784",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Camry",
            Latitude = 10.7612,
            Longitude = 106.6987,
            Address = "87 Võ Văn Tần, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Satin White",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 48000,
            LicensePlate = "51A-98712",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Impreza",
            Latitude = 10.8317,
            Longitude = 106.7634,
            Address = "46 Võ Văn Ngân, Linh Chiểu, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Lunar Silver",
            Seat = 5,
            FuelConsumption = 0.59M,
            Price = 47200,
            LicensePlate = "51A-23987",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "City",
            Latitude = 10.7426,
            Longitude = 106.7023,
            Address = "278 Nguyễn Tất Thành, Phường 13, Quận 4, TP.HCM",
        },
        new()
        {
            Color = "Desert Sand",
            Seat = 7,
            FuelConsumption = 0.75M,
            Price = 62000,
            LicensePlate = "51A-76543",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "GLC",
            Latitude = 10.7923,
            Longitude = 106.6871,
            Address = "139 Nguyễn Trãi, Phường 2, Quận 5, TP.HCM",
        },
        new()
        {
            Color = "Blazing Red",
            Seat = 5,
            FuelConsumption = 0.68M,
            Price = 53200,
            LicensePlate = "51A-45678",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "WRX",
            Latitude = 10.7791,
            Longitude = 106.6932,
            Address = "157 Nam Kỳ Khởi Nghĩa, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Glacier White",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 50500,
            LicensePlate = "51A-87632",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Altima",
            Latitude = 10.8065,
            Longitude = 106.7452,
            Address = "345 Kha Vạn Cân, Linh Đông, TP. Thủ Đức, TP.HCM",
        },
        new()
        {
            Color = "Mystic Blue",
            Seat = 4,
            FuelConsumption = 0.54M,
            Price = 61000,
            LicensePlate = "51A-34126",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model 3",
            Latitude = 10.7632,
            Longitude = 106.6819,
            Address = "76 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Sunset Red",
            Seat = 7,
            FuelConsumption = 0.72M,
            Price = 57500,
            LicensePlate = "51A-76598",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Discovery",
            Latitude = 10.8034,
            Longitude = 106.6629,
            Address = "222 Lê Văn Sỹ, Phường 14, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Misty Green",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 49800,
            LicensePlate = "51A-23476",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Legacy",
            Latitude = 10.7934,
            Longitude = 106.7234,
            Address = "178 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Mocha Brown",
            Seat = 7,
            FuelConsumption = 0.71M,
            Price = 55300,
            LicensePlate = "51A-65478",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Defender",
            Latitude = 10.7589,
            Longitude = 106.7032,
            Address = "287 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Velvet Purple",
            Seat = 4,
            FuelConsumption = 0.56M,
            Price = 59700,
            LicensePlate = "51A-87612",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "C40",
            Latitude = 10.7812,
            Longitude = 106.6943,
            Address = "145 Pasteur, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Polar White",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 52200,
            LicensePlate = "51A-98732",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Forester",
            Latitude = 10.8105,
            Longitude = 106.6574,
            Address = "378 Nguyễn Văn Cừ, Phường 4, Quận 5, TP.HCM",
        },
        new()
        {
            Color = "Golden Bronze",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 48900,
            LicensePlate = "51A-12398",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "NX",
            Latitude = 10.7654,
            Longitude = 106.7343,
            Address = "234 Bến Vân Đồn, Phường 1, Quận 4, TP.HCM",
        },
        new()
        {
            Color = "Titanium Grey",
            Seat = 7,
            FuelConsumption = 0.73M,
            Price = 61400,
            LicensePlate = "51A-43765",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Telluride",
            Latitude = 10.8215,
            Longitude = 106.7123,
            Address = "456 Nguyễn Tri Phương, Phường 4, Quận 10, TP.HCM",
        },
        //50
        new()
        {
            Color = "Midnight Purple",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 53800,
            LicensePlate = "51A-54321",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Mazda3",
            Latitude = 10.8032,
            Longitude = 106.6907,
            Address = "123 Ngô Gia Tự, Phường 2, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Arctic Silver",
            Seat = 7,
            FuelConsumption = 0.78M,
            Price = 62500,
            LicensePlate = "51A-76123",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Santa Fe",
            Latitude = 10.7645,
            Longitude = 106.6527,
            Address = "278 Cách Mạng Tháng 8, Phường 10, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Copper Sunset",
            Seat = 5,
            FuelConsumption = 0.56M,
            Price = 59700,
            LicensePlate = "51A-98217",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "ES",
            Latitude = 10.7893,
            Longitude = 106.7015,
            Address = "345 Hai Bà Trưng, Phường Tân Định, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Jade Green",
            Seat = 5,
            FuelConsumption = 0.52M,
            Price = 67000,
            LicensePlate = "51A-12789",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model Y",
            Latitude = 10.7732,
            Longitude = 106.6936,
            Address = "56 Trần Hưng Đạo, Phường Phạm Ngũ Lão, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Diamond White",
            Seat = 4,
            FuelConsumption = 0.62M,
            Price = 72400,
            LicensePlate = "51A-34987",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "C-Class",
            Latitude = 10.8012,
            Longitude = 106.6413,
            Address = "198 Hoàng Văn Thụ, Phường 9, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Moonlight Blue",
            Seat = 5,
            FuelConsumption = 0.69M,
            Price = 56800,
            LicensePlate = "51A-87123",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Sportage",
            Latitude = 10.7865,
            Longitude = 106.7156,
            Address = "234 Đinh Tiên Hoàng, Phường 1, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Ruby Red",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 49900,
            LicensePlate = "51A-45632",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "RAV4",
            Latitude = 10.7512,
            Longitude = 106.6834,
            Address = "76 Nguyễn Đình Chiểu, Phường 4, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Emerald Black",
            Seat = 7,
            FuelConsumption = 0.75M,
            Price = 67500,
            LicensePlate = "51A-65478",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Everest",
            Latitude = 10.7932,
            Longitude = 106.6854,
            Address = "123 Lý Chính Thắng, Phường 7, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Silk Blue",
            Seat = 5,
            FuelConsumption = 0.59M,
            Price = 53400,
            LicensePlate = "51A-23198",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Civic",
            Latitude = 10.7743,
            Longitude = 106.7032,
            Address = "456 Nguyễn Thị Minh Khai, Phường 2, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Platinum Gray",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 54700,
            LicensePlate = "51A-78934",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Focus",
            Latitude = 10.8123,
            Longitude = 106.6780,
            Address = "234 Bà Hạt, Phường 9, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Sunset Orange",
            Seat = 2,
            FuelConsumption = 0.86M,
            Price = 128000,
            LicensePlate = "51A-91234",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "911",
            Latitude = 10.7798,
            Longitude = 106.7005,
            Address = "89 Lê Lợi, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Crystal Blue",
            Seat = 4,
            FuelConsumption = 0.55M,
            Price = 63000,
            LicensePlate = "51A-45698",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Taycan",
            Latitude = 10.7654,
            Longitude = 106.7021,
            Address = "123 Nam Kỳ Khởi Nghĩa, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Deep Forest",
            Seat = 7,
            FuelConsumption = 0.72M,
            Price = 59800,
            LicensePlate = "51A-32198",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Palisade",
            Latitude = 10.7985,
            Longitude = 106.6943,
            Address = "456 Võ Thị Sáu, Phường 6, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Champagne Gold",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 57200,
            LicensePlate = "51A-89723",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Camry",
            Latitude = 10.7765,
            Longitude = 106.6698,
            Address = "78 Nguyễn Công Trứ, Phường Nguyễn Thái Bình, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Phantom Gray",
            Seat = 5,
            FuelConsumption = 0.66M,
            Price = 48500,
            LicensePlate = "51A-76543",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Mazda6",
            Latitude = 10.7632,
            Longitude = 106.6543,
            Address = "234 Phổ Quang, Phường 9, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Marina Blue",
            Seat = 5,
            FuelConsumption = 0.61M,
            Price = 51900,
            LicensePlate = "51A-12457",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Sonata",
            Latitude = 10.7912,
            Longitude = 106.7231,
            Address = "456 Khánh Hội, Phường 4, Quận 4, TP.HCM",
        },
        new()
        {
            Color = "Volcanic Red",
            Seat = 7,
            FuelConsumption = 0.74M,
            Price = 61200,
            LicensePlate = "51A-98432",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Fortuner",
            Latitude = 10.8132,
            Longitude = 106.6798,
            Address = "123 Tô Hiến Thành, Phường 13, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Aqua Teal",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 47400,
            LicensePlate = "51A-34521",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Jetta",
            Latitude = 10.7854,
            Longitude = 106.6321,
            Address = "789 Lý Thường Kiệt, Phường 7, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Celestial Silver",
            Seat = 5,
            FuelConsumption = 0.59M,
            Price = 52300,
            LicensePlate = "51A-65123",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Corolla",
            Latitude = 10.7698,
            Longitude = 106.6812,
            Address = "234 Lê Thánh Tôn, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Carbon Black",
            Seat = 5,
            FuelConsumption = 0.68M,
            Price = 64200,
            LicensePlate = "51A-87342",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "5 Series",
            Latitude = 10.7812,
            Longitude = 106.7098,
            Address = "456 Nguyễn Hữu Cảnh, Phường 22, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Pearl White",
            Seat = 4,
            FuelConsumption = 0.53M,
            Price = 57900,
            LicensePlate = "51A-21654",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model 3",
            Latitude = 10.7734,
            Longitude = 106.7034,
            Address = "78 Mạc Đĩnh Chi, Phường Đa Kao, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Burgundy Metallic",
            Seat = 7,
            FuelConsumption = 0.70M,
            Price = 56800,
            LicensePlate = "51A-98732",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Explorer",
            Latitude = 10.8045,
            Longitude = 106.7134,
            Address = "123 Hoàng Hoa Thám, Phường 12, Tân Bình, TP.HCM",
        },
        new()
        {
            Color = "Agate Black",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 49800,
            LicensePlate = "51A-45678",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "CX-5",
            Latitude = 10.7912,
            Longitude = 106.6734,
            Address = "456 Phan Đăng Lưu, Phường 3, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Glacier White",
            Seat = 5,
            FuelConsumption = 0.60M,
            Price = 55600,
            LicensePlate = "51A-76123",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Accord",
            Latitude = 10.7634,
            Longitude = 106.6821,
            Address = "789 Điện Biên Phủ, Phường 1, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Steel Blue",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 50700,
            LicensePlate = "51A-34567",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "A4",
            Latitude = 10.7832,
            Longitude = 106.6954,
            Address = "234 Cống Quỳnh, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM",
        },
        // 75
        new()
        {
            Color = "Metallic Bronze",
            Seat = 7,
            FuelConsumption = 0.71M,
            Price = 59500,
            LicensePlate = "51A-12478",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Everest",
            Latitude = 10.7556,
            Longitude = 106.6542,
            Address = "342 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Cosmic Gray",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 45600,
            LicensePlate = "51A-83521",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Altima",
            Latitude = 10.7712,
            Longitude = 106.7025,
            Address = "56 Nguyễn Du, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Electric Lime",
            Seat = 4,
            FuelConsumption = 0.51M,
            Price = 68900,
            LicensePlate = "51A-29765",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model S",
            Latitude = 10.7943,
            Longitude = 106.6987,
            Address = "178 Nam Kỳ Khởi Nghĩa, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Molten Red",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 53400,
            LicensePlate = "51A-74532",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Golf",
            Latitude = 10.7689,
            Longitude = 106.7045,
            Address = "321 Phạm Ngũ Lão, Phường Phạm Ngũ Lão, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Aurora White",
            Seat = 7,
            FuelConsumption = 0.78M,
            Price = 61200,
            LicensePlate = "51A-38596",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Land Cruiser",
            Latitude = 10.8102,
            Longitude = 106.6985,
            Address = "452 Lê Hồng Phong, Phường 1, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Lagoon Blue",
            Seat = 5,
            FuelConsumption = 0.58M,
            Price = 49800,
            LicensePlate = "51A-92147",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Camry",
            Latitude = 10.7561,
            Longitude = 106.6823,
            Address = "78 Trần Hưng Đạo, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Matte Black",
            Seat = 4,
            FuelConsumption = 0.69M,
            Price = 72300,
            LicensePlate = "51A-64328",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "718 Cayman",
            Latitude = 10.7875,
            Longitude = 106.7023,
            Address = "125 Tôn Đức Thắng, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Forest Emerald",
            Seat = 7,
            FuelConsumption = 0.76M,
            Price = 58700,
            LicensePlate = "51A-57934",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Q7",
            Latitude = 10.7723,
            Longitude = 106.6891,
            Address = "221 Nguyễn Thái Học, Phường Cầu Ông Lãnh, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Solar Gold",
            Seat = 5,
            FuelConsumption = 0.61M,
            Price = 51400,
            LicensePlate = "51A-78314",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "ES",
            Latitude = 10.7944,
            Longitude = 106.7229,
            Address = "394 Điện Biên Phủ, Phường 11, Quận 10, TP.HCM",
        },
        new()
        {
            Color = "Amethyst Purple",
            Seat = 5,
            FuelConsumption = 0.64M,
            Price = 49200,
            LicensePlate = "51A-45217",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "3 Series",
            Latitude = 10.8065,
            Longitude = 106.6754,
            Address = "102 Cách Mạng Tháng Tám, Phường 7, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Frozen Silver",
            Seat = 4,
            FuelConsumption = 0.53M,
            Price = 67800,
            LicensePlate = "51A-96432",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model X",
            Latitude = 10.7734,
            Longitude = 106.7059,
            Address = "258 Điện Biên Phủ, Phường 7, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Terracotta",
            Seat = 7,
            FuelConsumption = 0.77M,
            Price = 59600,
            LicensePlate = "51A-32765",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Defender",
            Latitude = 10.7568,
            Longitude = 106.6923,
            Address = "153 Võ Văn Tần, Phường 5, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Atlantic Blue",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 48700,
            LicensePlate = "51A-14587",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "RX",
            Latitude = 10.7892,
            Longitude = 106.7102,
            Address = "76 Trương Định, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Quantum Gray",
            Seat = 5,
            FuelConsumption = 0.59M,
            Price = 55200,
            LicensePlate = "51A-23549",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Impreza",
            Latitude = 10.8145,
            Longitude = 106.6754,
            Address = "289 Lý Thường Kiệt, Phường 15, Quận 11, TP.HCM",
        },
        new()
        {
            Color = "Sunrise Yellow",
            Seat = 2,
            FuelConsumption = 0.88M,
            Price = 125000,
            LicensePlate = "51A-87439",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "911",
            Latitude = 10.7754,
            Longitude = 106.7034,
            Address = "182 Pasteur, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Matrix Black",
            Seat = 5,
            FuelConsumption = 0.63M,
            Price = 47600,
            LicensePlate = "51A-39674",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Sonata",
            Latitude = 10.8023,
            Longitude = 106.6654,
            Address = "176 Võ Văn Kiệt, Phường Cô Giang, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Savannah Beige",
            Seat = 7,
            FuelConsumption = 0.74M,
            Price = 60800,
            LicensePlate = "51A-62158",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "GLE",
            Latitude = 10.7698,
            Longitude = 106.6934,
            Address = "263 Phạm Viết Chánh, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Pacific Blue",
            Seat = 5,
            FuelConsumption = 0.66M,
            Price = 49900,
            LicensePlate = "51A-75321",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Mazda3",
            Latitude = 10.8124,
            Longitude = 106.7215,
            Address = "118 Phan Văn Trị, Phường 12, Bình Thạnh, TP.HCM",
        },
        new()
        {
            Color = "Arctic Frost",
            Seat = 4,
            FuelConsumption = 0.52M,
            Price = 65400,
            LicensePlate = "51A-89637",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Model Y",
            Latitude = 10.7821,
            Longitude = 106.6934,
            Address = "95 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Amber Bronze",
            Seat = 5,
            FuelConsumption = 0.60M,
            Price = 51400,
            LicensePlate = "51A-41268",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "NX",
            Latitude = 10.7645,
            Longitude = 106.6824,
            Address = "267 Trần Hưng Đạo, Phường Cô Giang, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Cosmic Silver",
            Seat = 5,
            FuelConsumption = 0.65M,
            Price = 52800,
            LicensePlate = "51A-37459",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "WRX",
            Latitude = 10.7912,
            Longitude = 106.6821,
            Address = "326 Nguyễn Bỉnh Khiêm, Phường Đa Kao, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Sierra Brown",
            Seat = 7,
            FuelConsumption = 0.79M,
            Price = 63500,
            LicensePlate = "51A-95126",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Santa Fe",
            Latitude = 10.8032,
            Longitude = 106.7142,
            Address = "194 Hoàng Văn Thụ, Phường 9, Phú Nhuận, TP.HCM",
        },
        new()
        {
            Color = "Electric Cyan",
            Seat = 4,
            FuelConsumption = 0.54M,
            Price = 68700,
            LicensePlate = "51A-26793",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Electric,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "EV6",
            Latitude = 10.7843,
            Longitude = 106.6965,
            Address = "57 Alexandre de Rhodes, Phường Bến Nghé, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Urban Titanium",
            Seat = 5,
            FuelConsumption = 0.62M,
            Price = 47300,
            LicensePlate = "51A-83619",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Gasoline,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Civic",
            Latitude = 10.7712,
            Longitude = 106.6932,
            Address = "83 Calmette, Phường Nguyễn Thái Bình, Quận 1, TP.HCM",
        },
        new()
        {
            Color = "Azure Blue",
            Seat = 5,
            FuelConsumption = 0.67M,
            Price = 54800,
            LicensePlate = "51A-47296",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Hybrid,
            TransmissionType = TransmissionTypeNames.Automatic,
            Model = "Corolla",
            Latitude = 10.7954,
            Longitude = 106.7065,
            Address = "413 Hai Bà Trưng, Phường 8, Quận 3, TP.HCM",
        },
        new()
        {
            Color = "Slate Gray",
            Seat = 7,
            FuelConsumption = 0.73M,
            Price = 56900,
            LicensePlate = "51A-15728",
            Status = CarStatusEnum.Available,
            FuelType = FuelTypeNames.Diesel,
            TransmissionType = TransmissionTypeNames.Manual,
            Model = "Sorento",
            Latitude = 10.7798,
            Longitude = 106.6876,
            Address = "145 Nguyễn Đình Chiểu, Phường 6, Quận 3, TP.HCM",
        },
    ];

    public static async Task<Car[]> Execute(
        TransmissionType[] transmissionTypes,
        Model[] models,
        FuelType[] fuelTypes,
        TokenService tokenService,
        GeometryFactory geometryFactory
    )
    {
        var userTasks = Cars.Select(async u =>
        {
            await Task.Delay(0);
            string refreshToken = tokenService.GenerateRefreshToken();
            Guid newCarId = Uuid.NewDatabaseFriendly(Database.PostgreSql);

            var pickupLocation = geometryFactory.CreatePoint(
                new Coordinate(u.Longitude, u.Latitude)
            );
            pickupLocation.SRID = 4326;

            return new Car()
            {
                Id = newCarId,
                TransmissionTypeId = transmissionTypes
                    .Where(tt => tt.Name == u.TransmissionType)
                    .Select(tt => tt.Id)
                    .First(),
                ModelId = models.Where(tt => tt.Name == u.Model).Select(tt => tt.Id).First(),
                FuelTypeId = fuelTypes
                    .Where(tt => tt.Name == u.FuelType)
                    .Select(tt => tt.Id)
                    .First(),
                Status = u.Status,
                Color = u.Color,
                LicensePlate = u.LicensePlate,
                FuelConsumption = u.FuelConsumption,
                Price = u.Price,
                Seat = u.Seat,
                OwnerId = Guid.Parse("01951eae-12a7-756d-a8d5-bb1ee525d7b5"),
                PickupLocation = pickupLocation,
                PickupAddress = u.Address,
                CarStatistic = new() { CarId = newCarId, }
            };
        });
        return await Task.WhenAll(userTasks);
    }
}